### ISSUE TITLE
Change why link to opendatabutton.org/why

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/odb-chromeaddon#1]

**Comment by Steven-Eardley** [comment]
This is already the case. Changed in the release before last (0.8.4).

**Comment by JosephMcArthur** [comment]
Oh okay! It's not data.openaccessbutton.org/why then. I only just made the
page now.

Joe

On 10 March 2016 at 11:40, Steven Eardley <notifications@github.com> wrote:

> This is already the case. Changed in the release before last (0.8.4).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb-chromeaddon/issues/1#issuecomment-194785445>
> .
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by Steven-Eardley** [comment]
Yup, as of 10 days ago it was was pointing at a blank page awaiting that very change. Foresight on your part :)

The link is in the code [here](https://github.com/OAButton/odb-chromeaddon/blob/develop/js/ui.js#L281)

**Comment by JosephMcArthur** [comment]
Ah right. Next time can you give me a heads up ;)


On 10 March 2016 at 11:48, Steven Eardley <notifications@github.com> wrote:

> Yup, as of 10 days ago it was was pointing at a blank page awaiting that
> very change. Foresight on your part :)
>
> The link is in the code here
> <https://github.com/OAButton/odb-chromeaddon/blob/develop/js/ui.js#L281>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb-chromeaddon/issues/1#issuecomment-194787579>
> .
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>
